### ISSUE TITLE
CIFAR10-Adversarial-Perturbations.ipynb throws "OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized."

### ISSUE THREAD

**Issue by StevenDAdams** [mit-ll-responsible-ai/responsible-ai-toolbox#81]
When following CIFAR10-Adversarial-Perturbations.ipynb on a fresh Windows environment, trying to execute the step "Instantiate a data loader" throws an OMP: Error # 15.

> OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
> OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

Setting the environment variable "KMP_DUPLICATE_LIB_OK=TRUE" allows the example to run, without any apparent errors nor apparent incorrect results.

Versions:
torch 1.12.1
torchvision 0.13.1
rai-toolbox 0.2.1
rai-experiments 0.2.0rc2
matplotlib 3.5.1
tqdm 4.64.0

**Comment by rsokl** [comment]
I've encountered this before, but not in the context of running through the toolbox's tutorials. Does the issue persist if you reboot your machine?

There is nothing that we can do about this on our end – this is a torch/mkl issue – so I am going to close this issue. That being said, I am happy to continue to troubleshoot here.
